"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.
"""

from pathlib import Path

# BASE_DIR è la cartella root del progetto (dove c'è manage.py).
# Serve per costruire percorsi indipendenti dal PC (Windows/Mac/Linux).
BASE_DIR = Path(__file__).resolve().parent.parent

# In produzione SECRET_KEY deve stare fuori dal repo (variabili d'ambiente).
SECRET_KEY = 'django-insecure-=*%uyb5mt!45w(1906t90542&jh*f45(h!)gyls59^w=0p8j11'

# DEBUG=True mostra errori dettagliati (solo sviluppo).
# In produzione va messo False.
DEBUG = True

# In sviluppo lasciamo vuoto. In produzione si inseriscono i domini consentiti.
ALLOWED_HOSTS = []


# Applicazioni attive nel progetto.
# - le prime sono app di Django (admin, auth, sessioni, ecc.)
# - poi ci sono le nostre app: catalog, shopping_cart, orders, accounts
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "catalog",
    "shopping_cart",
    "orders",
    "accounts",
]

# Middleware: "filtri" che passano su ogni richiesta.
# Qui dentro ci sono componenti fondamentali come:
# - gestione sessioni
# - CSRF protection
# - autenticazione
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# File principale che contiene le URL del progetto (il "centralino").
ROOT_URLCONF = 'config.urls'

# Template engine:
# - DIRS include una cartella "templates" globale (utile per registration/login.html)
# - APP_DIRS=True permette a Django di cercare template dentro ogni app in app/templates/...
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            # context_processors aggiunge variabili utili a tutti i template
            # es: request, user autenticato, messaggi flash, ecc.
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database:
# usiamo SQLite per semplicità (come richiesto/consentito dalla traccia).
# Django crea il file db.sqlite3 nella root.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation:
# Queste regole controllano la qualità della password in registrazione.
# Nota: se vuoi "solo minimo 8 caratteri", si può lasciare solo MinimumLengthValidator.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # Regola: minimo 8 caratteri (di default)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Impostazioni lingua e timezone del progetto.
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static & Media:
# - STATIC: file del progetto (CSS/JS) serviti da /static/
# - MEDIA: file caricati (immagini prodotti) salvati in /media/
STATIC_URL = "/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# STATICFILES_DIRS: cartella dove metti assets statici personalizzati (es. style.css)
STATICFILES_DIRS = [BASE_DIR / "static"]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect dopo login/logout:
# così dopo login torni alla home, dopo logout torni alla home.
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
