# Generated by Django 5.2.10 on 2026-01-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_city_remove_order_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(default='---', max_length=100),
            preserve_default=False,
        ),
    ]
