# Generated by Django 5.2.10 on 2026-01-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_first_name_order_name_remove_order_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
